# -*- coding: utf-8 -*-
"""LinSimilarity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wWgeJIkrUUBb-nmGCttdfh1NUQBDGRCD
"""

from nltk.corpus import wordnet_ic
import nltk
nltk.download('wordnet_ic')
brown_ic = wordnet_ic.ic('ic-brown.dat')
semcor_ic = wordnet_ic.ic('ic-semcor.dat')

from nltk.corpus import wordnet as wn
from nltk.corpus import wordnet_ic
import nltk

# Download required data (only once)
nltk.download('wordnet')
nltk.download('wordnet_ic')

# Load the IC corpus (Brown corpus)
ic = wordnet_ic.ic('ic-brown.dat')

# Define two noun synsets
dog = wn.synset('dog.n.01')
cat = wn.synset('cat.n.01')

# Calculate Lin similarity (LCS computed internally)
similarity = dog.lin_similarity(cat, ic)

print("Lin similarity between dog and cat:", similarity)