# -*- coding: utf-8 -*-
"""Visualization of WordNet-sunburst.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MI2VuJvYJXKwkqvt1T4LhThb-aW6-Tt1
"""

import plotly.express as px
from nltk.corpus import wordnet as wn
import nltk

nltk.download('wordnet')

def get_sunburst_data(word):
    ids = []
    labels = []
    parents = []
    hover = []

    ids.append(word)
    labels.append(word)
    parents.append("")
    hover.append(f"Root word: {word}")

    for i, syn in enumerate(wn.synsets(word)):
        sense_id = f"{word}_sense_{i}"
        labels.append(f"Sense {i+1}")
        ids.append(sense_id)
        parents.append(word)
        hover.append(syn.definition())

        for j, hyper in enumerate(syn.hypernyms()):
            hyper_id = f"{sense_id}_hyper_{j}"
            ids.append(hyper_id)
            labels.append(f"Hypernym {j+1}")
            parents.append(sense_id)
            hover.append(hyper.definition())

    return ids, labels, parents, hover

def plot_sunburst_lexico(word):
    ids, labels, parents, hover = get_sunburst_data(word)
    fig = px.sunburst(
        names=labels,
        ids=ids,
        parents=parents,
        hover_data={'Definition': hover}
    )

    fig.update_traces(
        textinfo="label+percent parent",
        insidetextfont=dict(size=16),
        hoverlabel=dict(font_size=16),
    )

    fig.update_layout(
        title={
            'text': f"Lexicographic Sunburst Map for '{word}'",
            'y': 0.95,
            'x': 0.5,
            'xanchor': 'center',
            'yanchor': 'top',
            'font': dict(size=24)
        }
    )

    fig.show()

plot_sunburst_lexico("bank")