# -*- coding: utf-8 -*-
"""WSD-Lesk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FVvGG8QDCJy1XiC-Mosz9uUAj5tzFIsH
"""

pip install nltk

import nltk
from nltk.corpus import wordnet as wn
from nltk.wsd import lesk
from nltk.tokenize import word_tokenize
nltk.download('punkt_tab')

# Download necessary resources
nltk.download('wordnet')
nltk.download('punkt')
nltk.download('omw-1.4')

sentence = "He sat on the bank and watched the boats go by."
target_word = "bank"

# Tokenize the sentence
context = word_tokenize(sentence)

# Apply Lesk algorithm
sense = lesk(context, target_word)

print("Predicted sense:", sense)
print("Definition:", sense.definition())

for i, syn in enumerate(wn.synsets('bank')):
    print(f"{i + 1}. {syn.name()} - {syn.definition()}")

from nltk.corpus import wordnet as wn
from nltk.wsd import lesk
from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt')
nltk.download('wordnet')

def word_sense_disambiguation(sentence, target_word):
    tokens = word_tokenize(sentence)
    best_sense = lesk(tokens, target_word)

    ### we use the lesk() function from the nltk.wsd module to perform Word Sense Disambiguation.
    #### The lesk() function takes a list of tokens (obtained using word_tokenize()) and a target word.
    ##### It applies the Lesk algorithm to determine the best sense of the target word in the given context

    return best_sense.definition()

# Example usage
sentence = "I went to the bank to deposit my money."
target_word = "bank"

disambiguated_definition = word_sense_disambiguation(sentence, target_word)
print(f"Disambiguated Definition: {disambiguated_definition}")